spring:
  application:
    name: HeadacheChecker
  datasource:
    url: jdbc:postgresql://localhost:5432/headache_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: 'true'
        ddl-auto: create-drop
  liquibase:
    url: jdbc:postgresql://localhost:5432/headache_db
    password: postgres
    enabled: 'true'
    user: postgres
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: public
    drop-first: true
security:
  token: jartjhati984j7hde1n0lkhdeqoubfdrt42gimp0gfayt538kgnlojhs5jo0unga
  expiration: 86400000
logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG
      baklansbalkan:
        HeadacheChecker:
          security: DEBUG
          config: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
