spring:
  application:
    name: HeadacheChecker
  datasource:
    url: jdbc:postgresql://localhost:5432/headache_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: 'true'
        ddl-auto: create-drop
  liquibase:
    url: jdbc:postgresql://localhost:5432/headache_db
    password: postgres
    enabled: 'true'
    user: postgres
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: public
    drop-first: true