CREATE TABLE headache (
                          id INT GENERATED BY DEFAULT AS IDENTITY,
                          date DATE NOT NULL,
                          isheadache BOOLEAN,
                          ismedicine BOOLEAN,
                          medicine VARCHAR(50),
                          intensity INT CHECK (intensity >= 0 AND intensity < 6),
                          localisation VARCHAR(10),
                          timesofday VARCHAR(10),
                          comment VARCHAR(200),
                          createdat TIMESTAMP
);